### ISSUE TITLE
Transfer action to the reviewdog organization

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-flake8#1]
@haya14busa @mgrachev I created a small GitHub-action which allows users to lint Python source files and annotate them using reviewdog. To allow for more customization options I based this on the [py-actions/flake8 GitHub action](https://github.com/py-actions/flake8) instead of the normal [reviewdog/action-template](https://github.com/reviewdog/action-template). I put a transfer of ownership request to the reviewdog organization some minutes ago but as I was part of the organization this transfer request automatically went through. Sorry about that, I did not know I had enough permissions to do that without approval :man_facepalming:. I will open a discussion the next time before I click transfer ownership. Let me know what you think of the GitHub-action. Feel free to transfer it back to my personal account if the current implementation is not in line with to reviewdog roadmap. Here are some points we have to look at if we want to keep the repository under the reviewdog organization:

- [x] The code is currently licensed under a [Apache-2.0 License ](https://github.com/reviewdog/action-flake8/blob/master/LICENSE). If we want to license it under the MIT license like all the other GitHub actions I have to ask @chrissimpkins if it is okay to change the license for this fork.

- [x] I now use hyphens in the GitHub action input arguments I think it is wise to change them to underscores to be consistent with the rest of the review dog actions. Done in 4f9bd9a0

- [x] It might be an idea to add the bumpr and linter github action that is present in the other reviewdog actions. Done in 4f9bd9a0

- [x] I noticed that I can not release the latest release to the GitHub market place as an org admin first has to accept the terms.

**Comment by chrissimpkins** [comment]
Good to see you put this to use.   I'm glad to hear it.

>  If we want to license it under the MIT license like all the other GitHub actions I have to ask @chrissimpkins if it is okay to change the license for this fork.

I'd be happy to extend the license to either MIT or Apache 2.0.  Let me know if Apache is a blocker here and I can update the license upstream.

**Comment by haya14busa** [comment]
No problem, at all! Thank you for your work @rickstaa ! :+1:

> MIT or Apache 2.0

I actually don't have a strong preference, but it's easier to maintain if all reviewdog repos have the same LICENSE.

>  I now use hyphens in the GitHub action input arguments I think it is wise to change them to underscores to be consistent with the rest of the review dog actions

Cool! Just FYI: The additional reason why I used `_` instead of `-` as input argument is for GitHub environment variables especially for Docker action. GitHub automatically passes `INPUT_{ARGUMENT_NAME}` and hyphens (`-`) didn't work well with this.

> I noticed that I can not release the latest release to the GitHub market place as an org admin first has to accept the terms.

Let me check....

**Comment by haya14busa** [comment]
I accepted the terms and released the action to the market place.

**Comment by rickstaa** [comment]
Amazing! I just performed all the required changes. There is one action cron job that keeps failing but I opened [an issue](https://github.com/reviewdog/reviewdog/issues/832) for this on the review dog repo.

**Comment by rickstaa** [comment]
@haya14busa The release action still appears to be broken (see https://github.com/reviewdog/action-flake8/pull/21/checks?check_run_id=1602240516). It however does not give an informative warning message. This exact GitHub action recipe seems to work fine on all my other non-forked repositories (see https://github.com/rickstaa/action-get-semver/pull/6) for example.

**Comment by haya14busa** [comment]
You need to fix this condition if you want to post comments to PR, but it's actually not broken. If you merged the p-r, the bumper should work correctly.
https://github.com/haya14busa/action-bumpr/blob/2bf4d82ccaf51daca965a1567db7f2dcd72fec84/entrypoint.sh#L55

**Comment by rickstaa** [comment]
@haya14busa Ah I see thanks a lot. Isn't easier to just detach the fork?

**Comment by rickstaa** [comment]
@haya14busa Given the merge works it doesn't matter too much. Might cause confusion but I don't expect a lot of people other than me to work on this action.
