### ISSUE TITLE
Reviewdog Github Token write permissions

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-flake8#14]
It looks like this being a fork of another repository breaks the reviewdog github-pr-review feature ([see this github](https://github.com/reviewdog/action-flake8/runs/1554170922?check_suite_focus=true) action log). 

![image](https://user-images.githubusercontent.com/17570430/102407039-bdda5900-3feb-11eb-989f-e1777b080bff.png)

I  opened [a ticket](https://support.github.com/ticket/personal/0/945125) with the GitHub support to ask them to detach it.

**Comment by rickstaa** [comment]
@haya14busa Sorry to bother you but can you maybe add your approval to the ticket above. It is a ticket to detach this action from the upstream fork. I had to do this because the release action is failing.

**Comment by haya14busa** [comment]
p-r #13 is actually from forked repo, so it's expected.
![image](https://user-images.githubusercontent.com/3797062/102975796-f4f8bf00-4543-11eb-9ca4-3ec425fd3cba.png)

**Comment by rickstaa** [comment]
@haya14busa Ah I see. I thought it was because this is a fork of another repository. Do you think there is not need to detach the fork?

**Comment by haya14busa** [comment]
No need to detach the fork.

**Comment by rickstaa** [comment]
@haya14busa Great thanks, I will notify the GitHub agent.

**Comment by rickstaa** [comment]
@haya14busa The release action still appears to be broken. It, however, does not give an informative warning message (see [the log](https://github.com/reviewdog/action-flake8/pull/21/checks?check_run_id=1602240516)). Are you sure this is not caused by the repository being a fork? I use the same action.yml file on other repositories (see https://github.com/rickstaa/action-get-semver/pull/6)

**Comment by haya14busa** [comment]
dup: https://github.com/reviewdog/action-flake8/issues/1#issuecomment-750791957

**Comment by rickstaa** [comment]
@haya14busa Ah it did get posted after all sorry for that. The comment did not show up on my pc.
