### ISSUE TITLE
Detach fork from upstream

### ISSUE THREAD

**Issue by rickstaa** [reviewdog/action-flake8#26]
@haya14busa how is your opinion about detaching this fork from the upstream now that it doesn't share any code? This will result in both the release action comment working (not too big of a deal) and the [Github CLI](https://github.com/cli/cli) defaulting to the right upstream. If you think it is better to keep it attached due to related histories, this is also fine as I can also use the GitHub website to create my pull requests.

**Comment by rickstaa** [comment]
I just noticed the release action still is broken even when I push tags manually.

**Comment by haya14busa** [comment]
Please go ahead. I don't have strong preference.

**Comment by rickstaa** [comment]
@haya14busa Great I requested the detach. I think the only thing left to do is for you to approve it in the email thread.

**Comment by rickstaa** [comment]
@haya14busa I think the fork is also messing with the github marketplace release. It looks like version 3 is not released to the marketplace without you again accepting the terms.

![image](https://user-images.githubusercontent.com/17570430/104123502-d53b0680-534b-11eb-87a2-c3f73a34b884.png)

**Comment by rickstaa** [comment]
@haya14busa Seems to be something that happens on each major release it also affects:
- [reviewdog/action-black](https://github.com/marketplace/actions/run-black-formatter-with-reviewdog)
- [reviewdog/action-remark-lint](https://github.com/marketplace/actions/run-remark-lint-with-reviewdog)

Maybe you can re-accept the terms again.

**Comment by haya14busa** [comment]
I guess that's because the term was updated.

> Effective Date: January 1, 2021
> -- https://docs.github.com/en/free-pro-team@latest/github/site-policy/github-marketplace-developer-agreement

Done.

**Comment by rickstaa** [comment]
@haya14busa Ah I see thanks a lot for accepting the new agreement.
