### ISSUE TITLE
No module named pip on local runner

### ISSUE THREAD

**Issue by brianpaden289** [reviewdog/action-flake8#35]
When running on our local runner (Ubuntu 20.04) I see errors that pip does not exist. Suspect this is because our systems have python3.

[action-flake8] Installing reviewdog...
reviewdog/reviewdog info checking GitHub for tag 'v0.14.0'
reviewdog/reviewdog info found version: 0.14.0 for v0.14.0/Linux/x86_64
do_ypcall: clnt_call: RPC: Unable to receive; errno = No route to host
YPBINDPROC_DOMAIN: Domain not bound
reviewdog/reviewdog info installed /tmp/reviewdog
[action-flake8] Installing flake8 package...
/usr/bin/python: No module named pip

Manual testing:
$ python -m pip install flake8
/usr/bin/python: No module named pip

$  python3 -m pip install flake8
Collecting flake8
  Downloading flake8-4.0.1-py2.py3-none-any.whl (64 kB)

By installing python-is-python3 I can workaround on our machines but this will not work for environments where people need to explicitly call Python 2 and 3.

$ sudo apt install python-is-python3

**Comment by rickstaa** [comment]
@brianpaden289 Thanks for your interest in our action! I just created #36 to fix the problems you described. Can you maybe review #36 to see if it solves your problem?

**Comment by rickstaa** [comment]
I currently do not have the time to implement this. If somebody really needs it, he/she can pull #36, make the changes suggested in https://github.com/reviewdog/action-flake8/pull/36#issuecomment-1073244647 and open a new PR.
