### ISSUE TITLE
Make the 'errorformat' an input variable

### ISSUE THREAD

**Issue by salzmannsusan** [reviewdog/action-flake8#48]
The use of the pre-defined error format 'flake8' is hardcoded in the file entrypoint.sh. https://github.com/reviewdog/action-flake8/blob/1212bd6f1c67830dcff438cf39522d4b58407e71/entrypoint.sh#L25

When using self-written local plugins with flake8, the error format pre-defined in the flake8 excludes these user-defined errors to be picked up. In such a case the pre-defined error format pep8 is the more inclusive choice.

**Comment by rickstaa** [comment]
@salzmannsusan, thanks for your feature request and pull request! The `flake8` format used by our action is defined in the [reviewdog/errorformat](https://github.com/reviewdog/errorformat) repository.

https://github.com/reviewdog/errorformat/blob/33358de5bbea2dac9ca877f8b0d49ed4c0093417/fmts/python.go#L16-L24

See https://github.com/reviewdog/reviewdog?tab=readme-ov-file#input-format for more information. I added the [reviewdog_flags](https://github.com/reviewdog/action-flake8?tab=readme-ov-file#reviewdog_flags) input argument for use cases like yours. Can you see if setting reviewdog_flags to `"-f=pep8` works 🤔?

**Comment by haya14busa** [comment]
fixed by #49
